-- Group league matches into seasons. Existing matches belong to season 1 and
-- new matches are assigned to whichever season is marked as current.
create table public.league_seasons (
    id bigint generated by default as identity primary key,
    season_number integer not null unique check (season_number > 0),
    name text not null unique check (length(trim(name)) > 0),
    is_current boolean not null default false,
    created_at timestamptz not null default now()
);

create unique index league_seasons_one_current_idx
    on public.league_seasons (is_current)
    where is_current;

insert into public.league_seasons (season_number, name, is_current)
values (1, 'Temporada 1', true);

alter table public.friendly_matches
    add column season_id bigint;

update public.friendly_matches
set season_id = (
    select league_seasons.id
    from public.league_seasons
    where league_seasons.season_number = 1
);

alter table public.friendly_matches
    alter column season_id set not null,
    add constraint friendly_matches_season_id_foreign
        foreign key (season_id)
        references public.league_seasons(id)
        on delete restrict;

create index friendly_matches_season_played_on_idx
    on public.friendly_matches (season_id, played_on desc);

create or replace function private.assign_current_league_season()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.season_id is null then
        select league_seasons.id
        into new.season_id
        from public.league_seasons
        where league_seasons.is_current;
    end if;

    if new.season_id is null then
        raise exception 'A current league season is required' using errcode = '23514';
    end if;

    return new;
end;
$$;

revoke all on function private.assign_current_league_season()
from public, anon, authenticated;

create trigger assign_current_league_season
before insert on public.friendly_matches
for each row execute function private.assign_current_league_season();

create or replace function public.get_league_seasons()
returns table (
    id bigint,
    season_number integer,
    name text,
    is_current boolean,
    match_count bigint
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if not private.is_active_league_member() then
        raise exception 'Active league membership required' using errcode = '42501';
    end if;

    return query
    select
        seasons.id,
        seasons.season_number,
        seasons.name,
        seasons.is_current,
        count(matches.id) as match_count
    from public.league_seasons seasons
    left join public.friendly_matches matches
        on matches.season_id = seasons.id
    group by seasons.id
    order by seasons.season_number desc;
end;
$$;

drop function if exists public.get_public_friendly_matches();

create function public.get_public_friendly_matches(
    p_season_id bigint default null
)
returns table (
    id uuid,
    played_on date,
    team_a_score integer,
    team_b_score integer,
    team_a_penalty_score integer,
    team_b_penalty_score integer,
    season_id bigint,
    participants jsonb,
    goals jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
    v_season_id bigint;
begin
    if not private.is_active_league_member() then
        raise exception 'Active league membership required' using errcode = '42501';
    end if;

    v_season_id := p_season_id;

    if v_season_id is null then
        select seasons.id
        into v_season_id
        from public.league_seasons seasons
        where seasons.is_current;
    end if;

    if v_season_id is null then
        raise exception 'A current league season is required' using errcode = '23514';
    end if;

    return query
    select
        matches.id,
        matches.played_on,
        matches.team_a_score,
        matches.team_b_score,
        matches.team_a_penalty_score,
        matches.team_b_penalty_score,
        matches.season_id,
        coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'player_id', match_players.player_id,
                    'team', match_players.team,
                    'was_goalkeeper', match_players.was_goalkeeper
                )
                order by match_players.player_id
            )
            from public.match_players
            where match_players.match_id = matches.id
        ), '[]'::jsonb),
        coalesce((
            select jsonb_agg(
                jsonb_build_object(
                    'player_id', goals.scorer_player_id,
                    'team', goals.team,
                    'count', goals.goal_count,
                    'is_own_goal', goals.is_own_goal
                )
                order by goals.scorer_player_id
            )
            from public.goals
            where goals.match_id = matches.id
        ), '[]'::jsonb)
    from public.friendly_matches matches
    where matches.season_id = v_season_id
    order by matches.played_on desc;
end;
$$;

alter table public.league_seasons enable row level security;

revoke all privileges on table public.league_seasons
from public, anon, authenticated;

revoke all on function public.get_league_seasons()
from public, anon;

revoke all on function public.get_public_friendly_matches(bigint)
from public, anon;

grant execute on function public.get_league_seasons()
to authenticated;

grant execute on function public.get_public_friendly_matches(bigint)
to authenticated;

notify pgrst, 'reload schema';
